name: Debug Server Status

on:
  workflow_dispatch:
    inputs:
      debug_level:
        description: 'Debug level (basic/detailed)'
        required: false
        default: 'basic'
        type: choice
        options:
        - basic
        - detailed

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.VM_SSH_KEY }}" ]; then
            echo "Error: VM_SSH_KEY secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VM_IP }}" ]; then
            echo "Error: VM_IP secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VM_USER }}" ]; then
            echo "Error: VM_USER secret is not set"
            exit 1
          fi
          echo "All required secrets are present"
          
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts
          
      - name: Debug server status
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            echo "=== SYSTEM INFORMATION ==="
            uname -a
            echo ""
            
            echo "=== DISK SPACE ==="
            df -h
            echo ""
            
            echo "=== DOCKER STATUS ==="
            docker --version || echo "Docker not installed"
            docker compose version || docker-compose --version || echo "Docker Compose not available"
            sudo systemctl status docker --no-pager || echo "Docker service status unknown"
            echo ""
            
            echo "=== PROJECT DIRECTORY ==="
            PROJECT_DIR="$HOME/hbrm-test"
            if [ -d "$PROJECT_DIR" ]; then
              echo "✅ Project directory exists: $PROJECT_DIR"
              cd "$PROJECT_DIR"
              echo "Directory contents:"
              ls -la
              echo ""
              echo "Git status:"
              git status || echo "Not a git repository"
              echo ""
              echo "Scripts directory:"
              ls -la scripts/ || echo "Scripts directory not found"
              echo ""
              echo "Docker directory:"
              ls -la docker/ || echo "Docker directory not found"
              echo ""
              if [ -f ".env" ]; then
                echo "✅ .env file exists"
              else
                echo "❌ .env file missing"
              fi
              if [ -f ".env.example" ]; then
                echo "✅ .env.example file exists"
              else
                echo "❌ .env.example file missing"
              fi
            else
              echo "❌ Project directory not found: $PROJECT_DIR"
              echo "Home directory contents:"
              ls -la $HOME/
            fi
            echo ""
            
            echo "=== RUNNING CONTAINERS ==="
            docker ps -a || echo "Cannot list containers"
            echo ""
            
            echo "=== DOCKER IMAGES ==="
            docker images || echo "Cannot list images"
            echo ""
            
            echo "=== NETWORK CONNECTIVITY ==="
            ping -c 3 google.com || echo "No internet connectivity"
            echo ""
            
            echo "=== USER GROUPS ==="
            groups
            echo ""
            
            echo "=== ENVIRONMENT VARIABLES ==="
            echo "USER: $USER"
            echo "HOME: $HOME"
            echo "PATH: $PATH"
          EOF
