name: Debug Server Status

on:
  workflow_dispatch:
    inputs:
      debug_level:
        description: 'Debug level (basic/detailed)'
        required: false
        default: 'basic'
        type: choice
        options:
        - basic
        - detailed

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.VM_SSH_KEY }}" ]; then
            echo "Error: VM_SSH_KEY secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VM_IP }}" ]; then
            echo "Error: VM_IP secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VM_USER }}" ]; then
            echo "Error: VM_USER secret is not set"
            exit 1
          fi
          echo "✅ All required secrets are present"
          
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} 2>/dev/null >> ~/.ssh/known_hosts
          
      - name: Debug server status
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            echo "=== SYSTEM INFORMATION ==="
            uname -a || { echo "Failed to get system info"; exit 1; }
            echo ""
            
            echo "=== DISK SPACE ==="
            df -h || { echo "Failed to get disk space"; exit 1; }
            echo ""
            
            echo "=== DOCKER STATUS ==="
            if command -v docker &>/dev/null; then
              docker --version
              docker compose version 2>/dev/null || docker-compose --version 2>/dev/null || echo "Docker Compose not available"
              if command -v systemctl &>/dev/null; then
                sudo systemctl status docker --no-pager 2>/dev/null || echo "Docker service status unknown"
              else
                echo "Systemctl not available"
              fi
            else
              echo "Docker not installed"
            fi
            echo ""
            
            echo "=== PROJECT DIRECTORY ==="
            PROJECT_DIR="$HOME/hbrm-test"
            if [ -d "$PROJECT_DIR" ]; then
              echo "✅ Project directory exists: $PROJECT_DIR"
              cd "$PROJECT_DIR" || { echo "Cannot cd into project dir"; exit 1; }
              echo "Directory contents:"
              ls -la
              echo ""
              echo "Git status:"
              git status 2>/dev/null || echo "Not a git repository"
              echo ""
              echo "Scripts directory:"
              ls -la scripts/ 2>/dev/null || echo "Scripts directory not found"
              echo ""
              echo "Docker directory:"
              ls -la docker/ 2>/dev/null || echo "Docker directory not found"
              echo ""
              [ -f ".env" ] && echo "✅ .env file exists" || echo "❌ .env file missing"
              [ -f ".env.example" ] && echo "✅ .env.example file exists" || echo "❌ .env.example file missing"
            else
              echo "❌ Project directory not found: $PROJECT_DIR"
              echo "Home directory contents:"
              ls -la "$HOME"
            fi
            echo ""
            
            echo "=== RUNNING CONTAINERS ==="
            docker ps -a 2>/dev/null || echo "Cannot list containers"
            echo ""
            
            echo "=== DOCKER IMAGES ==="
            docker images 2>/dev/null || echo "Cannot list images"
            echo ""
            
            echo "=== NETWORK CONNECTIVITY ==="
            ping -c 3 google.com 2>/dev/null || echo "No internet connectivity"
            echo ""
            
            echo "=== USER GROUPS ==="
            groups || echo "Cannot list groups"
            echo ""
            
            echo "=== ENVIRONMENT VARIABLES ==="
            echo "USER: $USER"
            echo "HOME: $HOME"
            echo "PATH: $PATH"
          EOF
