name: Example Manual Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      message:
        description: 'Custom message to display'
        required: false
        default: 'Hello World'
        type: string
      enable_debug:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean
      version:
        description: 'Version number'
        required: true
        type: string

jobs:
  manual-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Display inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Message: ${{ github.event.inputs.message }}"
          echo "Debug enabled: ${{ github.event.inputs.enable_debug }}"
          echo "Version: ${{ github.event.inputs.version }}"
          
      - name: Conditional step based on input
        if: github.event.inputs.enable_debug == 'true'
        run: |
          echo "Debug mode is enabled!"
          echo "Running additional debug commands..."
          
      - name: Environment-specific step
        run: |
          if [ "${{ github.event.inputs.environment }}" = "production" ]; then
            echo "Deploying to PRODUCTION environment"
            echo "Extra safety checks enabled"
          else
            echo "Deploying to STAGING environment"
            echo "Fast deployment mode"
          fi
