name: Fix n8n Secure Cookie Issue

on:
  workflow_dispatch:

jobs:
  fix-cookies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.VM_SSH_KEY }}" ]; then
            echo "Error: VM_SSH_KEY secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VM_IP }}" ]; then
            echo "Error: VM_IP secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VM_USER }}" ]; then
            echo "Error: VM_USER secret is not set"
            exit 1
          fi
          
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts
          
      - name: Fix n8n secure cookie configuration
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            echo "🔧 Fixing n8n secure cookie configuration..."
            
            cd $HOME/hbrm-test
            
            # Check current .env file
            echo "Current .env file:"
            cat .env
            echo ""
            
            # Add N8N_SECURE_COOKIE=false if not present
            if ! grep -q "N8N_SECURE_COOKIE" .env; then
              echo "Adding N8N_SECURE_COOKIE=false to .env file..."
              echo "N8N_SECURE_COOKIE=false" >> .env
            else
              echo "Updating N8N_SECURE_COOKIE to false..."
              sed -i 's/N8N_SECURE_COOKIE=.*/N8N_SECURE_COOKIE=false/' .env
            fi
            
            echo ""
            echo "Updated .env file:"
            cat .env
            echo ""
            
            # Restart n8n container to apply changes
            echo "Restarting n8n container to apply changes..."
            
            # Determine Docker Compose command
            if command -v docker-compose &> /dev/null; then
              DOCKER_COMPOSE_CMD="docker-compose"
            else
              DOCKER_COMPOSE_CMD="docker compose"
            fi
            
            echo "Using: $DOCKER_COMPOSE_CMD"
            
            # Restart the container
            $DOCKER_COMPOSE_CMD -f docker/docker-compose.n8n.yml restart
            
            # Wait for container to start
            echo "Waiting for n8n to restart..."
            sleep 15
            
            # Check if container is running
            if docker ps | grep -q n8n; then
              echo "✅ n8n container restarted successfully!"
              
              # Get public IP
              PUBLIC_IP=$(curl -s ifconfig.me)
              
              echo ""
              echo "🎉 n8n secure cookie issue fixed!"
              echo "🌐 Access n8n at: http://$PUBLIC_IP:5678"
              echo "🔐 Username: admin"
              echo "🔐 Password: changeme"
              echo ""
              echo "The secure cookie error should now be resolved."
              
            else
              echo "❌ Failed to restart n8n container"
              echo "Container status:"
              docker ps -a | grep n8n
            fi
          EOF
