name: Setup Custom Domain for n8n

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Your domain (e.g., n8n.yourdomain.com)'
        required: true
        type: string
      email:
        description: 'Email for SSL certificate notifications'
        required: true
        type: string
      setup_type:
        description: 'Type of setup to perform'
        required: true
        default: 'ssl_only'
        type: choice
        options:
        - ssl_only
        - full_setup
        - test_domain
      force_renewal:
        description: 'Force SSL certificate renewal'
        required: false
        default: false
        type: boolean

jobs:
  setup-domain:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate inputs
        run: |
          echo "Domain: ${{ github.event.inputs.domain }}"
          echo "Email: ${{ github.event.inputs.email }}"
          echo "Setup type: ${{ github.event.inputs.setup_type }}"
          echo "Force renewal: ${{ github.event.inputs.force_renewal }}"
          
          # Basic domain validation
          if [[ ! "${{ github.event.inputs.domain }}" =~ ^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}$ ]]; then
            echo "Error: Invalid domain format"
            exit 1
          fi
          
      - name: Test domain DNS
        if: github.event.inputs.setup_type == 'test_domain'
        run: |
          echo "Testing DNS resolution for ${{ github.event.inputs.domain }}"
          nslookup ${{ github.event.inputs.domain }} || echo "DNS not resolved yet"
          
      - name: Setup SSL certificate
        if: github.event.inputs.setup_type != 'test_domain'
        run: |
          echo "Setting up SSL for ${{ github.event.inputs.domain }}"
          echo "Email: ${{ github.event.inputs.email }}"
          echo "Force renewal: ${{ github.event.inputs.force_renewal }}"
          
          # Here you would call your actual SSL setup logic
          echo "SSL setup completed!"
          
      - name: Full setup
        if: github.event.inputs.setup_type == 'full_setup'
        run: |
          echo "Performing full n8n setup with domain ${{ github.event.inputs.domain }}"
          # Here you would call your full setup workflow
          echo "Full setup completed!"
