name: Test Workflow Dispatch

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Simple test
        run: |
          echo "🧪 Testing workflow_dispatch functionality"
          echo "Current time: $(date)"
          echo "✅ workflow_dispatch is working correctly!"
